export const portfolioProfile = {
  name: "Mohammed El Kassoiri",
  title: "Data Scientist & MACHINE LEARNING Engineer",
  specialization: "Machine Learning, Deep Learning, Computer Vision, and NLP",
  location: "Morocco",
  status: "Available for full-time AI and Data Science opportunities",
  internship:
    "Data Science & Machine Learning Intern at XAI Morocco (Aug 2025 – Oct 2025)",
  technologies: [
    "Python",
    "PyTorch",
    "TensorFlow",
    "FastAPI",
    "Computer Vision",
    "NLP",
    "Remote Sensing",
    "Google Earth Engine",
    "React",
    "Next.js",
    "TypeScript",
  ],
  researchInterests: [
    "Agricultural AI",
    "Semantic Segmentation",
    "Satellite Image Analysis",
    "Multilingual NLP",
  ],
  projects: [
    "Automatic Agricultural Parcelization",
    "English to Darija Translation",
    "Medical-Diagnosis-COT-DeepSeek",
    "MY LAW Moroccan Legal RAG",
  ],
  cvUrl: "/Mohammed_el_kassoiri.pdf",
  contact: {
    email: "mohammed.kassoiri@gmail.com",
    linkedin: "https://linkedin.com/in/Mohammed-El-Kassoiri",
    github: "https://github.com/Mohammed-El-Kassoiri",
  },
} as const
